### ISSUE TITLE
Determining Problems to Solve

### ISSUE THREAD

**Issue by x3haloed** [torus-online/torus#1]
We need to select a set of problems in the open source ecosystem to solve that will support our mission to drive stability and productivity. The first stage will be to brainstorm, and then we will discuss which of the problems is the right set in support of our goals.

**Comment by x3haloed** [comment]
Here's an excellent starting point: https://www.reddit.com/r/opensource/comments/hd0007/open_source_developers_what_incentivizes_you/

It really seems like the major issues stem from collaboration -- how do you get all these people to work together and treat each other with respect? How do you keep them working towards a common vision?

**Comment by x3haloed** [comment]
The main problem to solve is stability. The important issues brought up in the reddit thread are:

1. Lack of funding
1. Missing teamwork
1. Lack of visionary leadership

We should choose from these.

**Comment by orphanpeachpage** [comment]
Pick one to focus on?

**Comment by x3haloed** [comment]
Umm, not necessarily just one, but try to address one or more through one or more solutions.

**Comment by x3haloed** [comment]
It seems that the model we've chosen so far could address these issues together. Treasury + shareholders + board members. To borrow from @rin9s:
![image](https://user-images.githubusercontent.com/1995994/85346979-046f5080-b4ac-11ea-96a8-b50f7c3320ef.png)

**Comment by x3haloed** [comment]
Since funding comes up over and over again, here’s a nice piece about open source funding and what’s being tried right now:

https://plausible.io/blog/open-source-funding
